name: movil_inmobiliaria
description: 'A new Flutter project.'
publish_to: 'none' 

version: 1.0.0+1

environment:
  # Corregido: Indentación correcta y rango de versión recomendado
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Tus dependencias existentes ---
  go_router: ^7.0.0
  open_file: ^3.3.1
  shared_preferences: ^2.1.0
  http: ^1.2.1
  path_provider: ^2.1.1
  web_socket_channel: ^3.0.2
  provider: ^6.0.5
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.1
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  share_plus: ^12.0.0
  fl_chart: ^0.68.0
  flutter_markdown: ^0.7.3
  
  # --- Dependencias añadidas para la nueva vista ---
  lucide_flutter: any
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf